public enum TokenType {
    KEYWORD,
    IDENTIFIER,
    INT_LITERAL,
    FLOAT_LITERAL,
    STRING_LITERAL,
    CHAR_LITERAL,
    BOOLEAN_LITERAL,
    OP_ARITHMETIC,
    OP_RELATIONAL,
    OP_LOGICAL,
    OP_ASSIGNMENT,
    OP_INC_DEC,
    PUNCTUATOR,
    COMMENT,
    EOF,
    ERROR
}
